export { BookingIcon } from './BookingIcon'
export { HandshakeIcon } from './HandshakeIcon'
export { TrainingIcon } from './TrainingIcon'
export { ClipIcon } from './ClipIcon'
export { CheckinIcon } from './CheckinIcon'
export { PersonIcon } from './PersonIcon'
export { OfficeIcon } from './OfficeIcon'
